[[plugins]]
repo = 'Shougo/dein.vim'

### colorscheme {{{
#[[plugins]]
#repo = 'illicium/vim-colors-solarized'
#rev = 'cb5b184d05dece1b7ed74ad2313f009bb18f63fc'

[[plugins]]
repo = 'cocopon/iceberg.vim'

#[[plugins]]
#repo = 'joshdick/onedark.vim'

#[[plugins]]
#repo = 'jacoborus/tender.vim'
### }}}

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'LeafCage/yankround.vim'

[[plugins]]
repo = 't9md/vim-quickhl'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'tmhedberg/matchit'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'LeafCage/foldCC.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

#[[plugins]]
#repo = 'nixprime/cpsm'
#repo = 'ptzz/cpsm'
#build = 'env PY3=ON ./install.sh'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = ['lightline.vim', 'ale']

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'cohama/lexima.vim'

### vim-operator-user {{{
[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'vim-operator-user'

[[plugins]]
repo = 'osyo-manga/vim-operator-search'
depends = 'vim-operator-user'
### }}}

### vim-textobj {{{
[[plugins]]
repo = 'kana/vim-textobj-user'

#[[plugins]]
# af, if
#repo = 'kana/vim-textobj-function'

#[[plugins]]
#repo = 'kentaro/vim-textobj-function-php'
#depends = 'vim-textobj-function'

[[plugins]]
# al, il
repo = 'kana/vim-textobj-line'

[[plugins]]
# ada, ida
repo = 'kana/vim-textobj-datetime'

[[plugins]]
# ac, ic
repo = 'thinca/vim-textobj-comment'

[[plugins]]
# asb, isb
repo = 'osyo-manga/vim-textobj-multiblock'

[[plugins]]
# ao, io
repo = 'glts/vim-textobj-indblock'
### }}}
