### Unite {{{
[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
on_cmd = ['VimFiler', 'VimFilerBufferDir']

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = 'unite.vim'

[[plugins]]
repo = 'tsukkee/unite-tag'
on_source = 'unite.vim'

[[plugins]]
repo = 'osyo-manga/unite-quickfix'
on_source = 'unite.vim'

[[plugins]]
repo = 'thinca/vim-qfreplace'
on_source = 'unite.vim'
### }}}

### completion {{{
[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
if = "has('nvim')"
on_i = 1
[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_if = 1

[[plugins]]
repo = 'Shougo/echodoc'
on_if = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_i  = 1
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'lvht/phpcd.vim'
build = 'composer install'
## }}}

### Gundo {{{
[[plugins]]
repo = 'sjl/gundo.vim'
on_cmd = 'GundoToggle'
### }}}

### PHP {{{
### }}}

### Golang {{{
[[plugins]]
repo = 'fatih/vim-go'
### }}}

### syntax {{{
[[plugins]]
repo = 'cespare/vim-toml'
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
[[plugins]]
repo = 'othree/html5-syntax.vim'
[[plugins]]
repo = 'othree/javascript-syntax.vim'
[[plugins]]
repo = 'tpope/vim-markdown'
[[plugins]]
repo = 'StanAngeloff/php.vim'
hook_add = '''
function! PhpSyntaxOverride()
  hi! def link phpDocTags  phpDefine
  hi! def link phpDocParam phpType
endfunction
augroup phpSyntaxOverride
  autocmd!
  autocmd FileType php call PhpSyntaxOverride()
augroup END
'''
[[plugins]]
repo = 'jwalton512/vim-blade'
### }}}

### indent {{{
[[plugins]]
repo = 'othree/html5.vim'
[[plugins]]
repo = 'jiangmiao/simple-javascript-indenter'
[[plugins]]
repo = '2072/PHP-Indenting-for-VIm'
[[plugins]]
repo = 'stephpy/vim-yaml'
### }}}
